// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Image theme suggestion AI agent.
 *
 * - suggestImageThemes - A function that handles the image theme suggestion process.
 * - SuggestImageThemesInput - The input type for the suggestImageThemes function.
 * - SuggestImageThemesOutput - The return type for the suggestImageThemes function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SuggestImageThemesInputSchema = z.object({
  photoUrl: z.string().describe('The URL of the uploaded photo.'),
});
export type SuggestImageThemesInput = z.infer<typeof SuggestImageThemesInputSchema>;

const SuggestImageThemesOutputSchema = z.object({
  themes: z
    .array(z.string())
    .describe(
      'An array of suggested themes based on the image content, style, and mood.'
    ),
});
export type SuggestImageThemesOutput = z.infer<typeof SuggestImageThemesOutputSchema>;

export async function suggestImageThemes(input: SuggestImageThemesInput): Promise<SuggestImageThemesOutput> {
  return suggestImageThemesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestImageThemesPrompt',
  input: {
    schema: z.object({
      photoUrl: z.string().describe('The URL of the uploaded photo.'),
    }),
  },
  output: {
    schema: z.object({
      themes: z
        .array(z.string())
        .describe(
          'An array of suggested themes based on the image content, style, and mood.'
        ),
    }),
  },
  prompt: `You are an AI assistant designed to suggest themes for poems based on images.

  Analyze the image at the provided URL and suggest three themes that would be suitable for generating a poem.
  Consider the image's content, style, and mood when suggesting themes.

  The photo URL is: {{media url=photoUrl}}
  Themes:`,
});

const suggestImageThemesFlow = ai.defineFlow<
  typeof SuggestImageThemesInputSchema,
  typeof SuggestImageThemesOutputSchema
>({
  name: 'suggestImageThemesFlow',
  inputSchema: SuggestImageThemesInputSchema,
  outputSchema: SuggestImageThemesOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
